#!/bin/sh

# Remove prompt space; suppress errors
unsetopt PROMPT_SP 2>/dev/null

# Default programs:
export EDITOR="nvim"

# Ensure default paths exist
mkdir -p -m 755 $HOME/{.config/{ansible,docker,m2,npm/{global,cache},zsh},.local/{bin,share},.cache/{lemminx,zsh_sessions}}
mkdir -p -m 700 $HOME/.config/kube

# Cleanup $HOME
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_LOCAL_HOME="$HOME/.local"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSH="$ZDOTDIR/.oh-my-zsh"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
# export KUBECONFIG="$XDG_CONFIG_HOME/kube"
export MAVEN_USER_HOME="$XDG_CONFIG_HOME/m2"
export NPM_CONFIG_PREFIX="$XDG_CONFIG_HOME/npm/global"
export NPM_CONFIG_CACHE="$XDG_CONFIG_HOME/npm/cache"
export ZSH_SESSION_DIR="$XDG_CACHE_HOME/zsh_sessions"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
export DOTFILES_PATH="$HOME/.dotfiles"

# Soft linking immutable paths
[[ ! -L "$HOME/.docker" ]] && ln -s "$DOCKER_CONFIG" "$HOME/.docker"
[[ ! -L "$HOME/.lemminx" ]] && ln -s "$XDG_CACHE_HOME/lemminx" "$HOME/.lemminx"

# Add all directories in `$HOME/.local/bin` to $PATH
export PATH="$PATH:$(find $XDG_LOCAL_HOME/bin -type d | paste -sd ':' -)"

# Export macOS Homebrew
if [[ "$(uname)" == "Darwin" ]]; then
  HOMEBREW="/opt/homebrew/bin:/opt/homebrew/sbin"
  export PATH="$PATH:$HOMEBREW"
fi

# Enable Biometrics in macOS
if [[ "$(uname)" == "Darwin" ]]; then
  line="auth       sufficient     pam_tid.so"
  grep -qF "$line" /etc/pam.d/sudo || {
    printf "\033[1;33m>\033[0;36m Enter your password to enable CLI Biometrics (prompt only once).\n\033[0m"
    sudo sed -i '' '2s|^|'"$line"'\n|' /etc/pam.d/sudo
  }
fi

# GCP
export USE_GKE_GCLOUD_AUTH_PLUGIN=True

