#!/bin/sh

# Remove prompt space; suppress errors
unsetopt PROMPT_SP 2>/dev/null

# Default programs:
export EDITOR="nvim"

# Ensure default paths exist
mkdir -p -m 755 $HOME/{.config/{ansible,docker,m2,zsh},.local/{bin,share},.cache/zsh_sessions}
mkdir -p -m 700 $HOME/.config/kube

# Cleanup $HOME
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_LOCAL_HOME="$HOME/.local"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export KUBECONFIG="$XDG_CONFIG_HOME/kube"
export MAVEN_USER_HOME="$XDG_CONFIG_HOME/m2"
export ZSH_SESSION_DIR="$XDG_CACHE_HOME/zsh_sessions"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
export DOTFILES_PATH="$HOME/.dotfiles"

# Soft linking immutable paths
[[ ! -L "$HOME/.docker" ]] && ln -s "$DOCKER_CONFIG" "$HOME/.docker"

# Add all directories in `$HOME/.local/bin` to $PATH
export PATH="$PATH:$(find $XDG_LOCAL_HOME/bin -type d | paste -sd ':' -)"

# Export macOS Homebrew
if [[ "$(uname)" == "Darwin" ]]; then
  HOMEBREW="/opt/homebrew/bin:/opt/homebrew/sbin"
  export PATH="$PATH:$HOMEBREW"
fi